### ISSUE TITLE
Connect edurain.org and app.edurain.org

### ISSUE THREAD

**Issue by MokshkSingh** [EduRAIN/edurain-client#101]

**Comment by tomdng** [comment]
<img width="1326" alt="Screen Shot 2020-11-26 at 5 07 32 PM" src="https://user-images.githubusercontent.com/28582336/100396200-e1703c00-3009-11eb-9471-2176fb7d245f.png">
The `GET AID NOW` link the top right takes you from edurain.org to app.edurain.org
