### ISSUE TITLE
Finalize Color Palette

### ISSUE THREAD

**Issue by wbvtler** [EduRAIN/edurain-client#11]
There needs to be a consistent set of brand/site colors. Right now there are too many different colors and none of them are defined.

![colors](https://user-images.githubusercontent.com/29716496/84170326-2f36bf00-aa3f-11ea-9606-d689944ad200.png)

---

![colors2](https://user-images.githubusercontent.com/29716496/84170456-5b524000-aa3f-11ea-8868-7126f3ea3f75.png)

**Comment by karur22** [comment]
@wbvtler I used random shades of purple for wireframing purposes. I just emailed you the official logo of eduRain, which has the proper shade of purple on it.

**Comment by bryonakabk** [comment]
Can you create a document with exact color shades?

Random shades is not a proper answer for this question.

Thank you,
Bryon 



Sent from App for Gmail


Tuesday, June 9, 2020, 12:14 PM -0500 from notifications@github.com  <notifications@github.com>:

**Comment by wbvtler** [comment]
@karur22 @bryonakabk We should have a name and purpose, ie. "primary", "accent-green", "accent-orange", "disabled", "important".

**Comment by wbvtler** [comment]
Completed in Slack

https://drive.google.com/drive/u/3/folders/1g6FyMIxUXa43fi2zdIhkvWwZcMCSdS5l
