### ISSUE TITLE
Number, dollar input

### ISSUE THREAD

**Issue by wbvtler** [EduRAIN/edurain-client#18]
Not totally sure what the best way to do this would be. It would be nice if we could give the component "types" of dollar and number, with dollar including the extra decorations.

![number_dollar_input](https://user-images.githubusercontent.com/29716496/84174593-69568f80-aa44-11ea-9cc7-a54fb0bb6776.png)

**Comment by tomdng** [comment]
I've created a number component but I do have some questions about how the final component is gonna act. So far I'm preventing the user from adding decimals, and when the user adds a negative number, the form input becomes invalid and glows red.

Aside from all that do we want the users to be able to add commas to numbers? Or do we want to add in the commas ourselves so the user can't make a mistake? Or should we not allow users to input commas whatsoever?

**Comment by wbvtler** [comment]
@tomdng While this is not a high priority at this time, what is the purpose of preventing decimals?

**Comment by arronz99** [comment]
The user will input income which is usually in whole number amounts, we’ll automatically going to assume the number ends with “.00”

**Comment by wbvtler** [comment]
@tomdng I would suggest using something like `<input type="number" min="0.01" step="0.01" />`

**Comment by tomdng** [comment]
Sure, I'll go and do that and make sure that the inputs work with decimal numbers then.
