### ISSUE TITLE
Find - Styling fixes

### ISSUE THREAD

**Issue by wbvtler** [EduRAIN/edurain-client#64]
1. On click of Find open Questionaire by default.
2. The checkbox list under the search bar should be symmetrical in display with the rest of the content on the page.
4. In the questionnaire once next is clicked the focus should be moved to the top of the next page.
5. At the end of the questionnaire have reasonable buttons to edit and to view scholarships that would close the pop-up and display scholarships.
6. The scholarship display for the post questionnaire result and post search result to be in sync.

**Comment by wbvtler** [comment]
Re `2`: It is not possible to change the way algolia stacks their suggested filters. However, it is possible to limit the number of filters shown, so only the few most relevant are displayed at a time.

**Comment by wbvtler** [comment]
@arronz99 can you give some insight on `#5`? I don't remember what to do here.

**Comment by arronz99** [comment]
> @arronz99 can you give some insight on `#5`? I don't remember what to do here.

So that's just their way of saying there shouldn't be stuff displayed in beginning and scholarships should update along with questionnaire. That will be more of a algolia thing, I'll take care of the whole matching filters with questions/responses
